version: "3.9"
services:
  postgres:
    image: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
  api-gateway:
    build:
      context: .
      dockerfile: ./dev.Dockerfile
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/caucision_development
    dns:
      - 8.8.8.8
      - 1.1.1.1
    ports:
      - "2300:2300"

volumes:
  db-data:
