version: "3.9"
services:

  scylla:
    image: scylladb/scylla:5.1.0
    restart: always
    ports:
    - "9042:9042"
    - "10000:10000"

  postgres:
    image: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  api-gateway:
    container_name: api-gateway
    build:
      context: .
      dockerfile: ./dev.Dockerfile
    depends_on:
      - postgres
      - scylla
      - rabbitmq
      - redis
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/caucision_development
      REDIS_URL: redis://redis:6379
      SCYLLA_HOST: scylla
      RABBIT_MQ_HOST: rabbitmq
    dns:
      - 8.8.8.8
      - 1.1.1.1
    ports:
      - "2300:2300"

  redis:
    image: redis:7.0.10
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - cache:/data

  rabbitmq:
    image: rabbitmq:3.11.16-management
    restart: always
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - message-queue:/var/lib/rabbitmq

  caucision-ml-celery:
    image: hoangvu03081/caucision-ml-celery:0.3
    restart: always
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/caucision_development
      SCYLLA_HOST: scylla
      REDIS_URL: redis://redis:6379
      CELERY_BROKER_URL: pyamqp://guest:guest@rabbitmq
    depends_on:
      - postgres
      - scylla
      - rabbitmq

volumes:
  db-data:
  cache:
  message-queue:
