version: "3.9"
services:

  scylla:
    image: scylladb/scylla:5.1.0
    restart: always
    ports:
    - "9042:9042"
    - "10000:10000"

  postgres:
    image: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  api-gateway:
    container_name: api-gateway
    build:
      context: .
      dockerfile: ./dev.Dockerfile
    depends_on:
      - postgres
      - scylla
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/caucision_development
    dns:
      - 8.8.8.8
      - 1.1.1.1
    ports:
      - "2300:2300"

  redis:
    image: redis:7.0.10
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - cache:/data

volumes:
  db-data:
  cache:
